---
kind: "Deployment"
apiVersion: "apps/v1"
metadata:
  name: nginx-rp-test
  labels:
    app.kubernetes.io/name: nginx
    app.kubernetes.io/instance: nginx
spec:
  replicas: 1 
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx
      app.kubernetes.io/instance: "nginx"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nginx
        app.kubernetes.io/instance: nginx
    spec:
      containers:
      - name: "nginx"
        image: "public.ecr.aws/nginx/nginx:alpine"
        ports:
        - containerPort: 8080
          protocol: "TCP"
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "nginx-svc"
  labels:
    app: "nginx"
spec:
  type: "ClusterIP"
  selector:
    app.kubernetes.io/name: nginx
    app.kubernetes.io/instance: "nginx"
  ports:
  - port: 8080
    protocol: "TCP"